[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.rpc_endpoints]
paseo = "https://testnet-passet-hub-eth-rpc.polkadot.io"
base = "https://base-sepolia-rpc.publicnode.com"
eth = "https://eth-sepolia-testnet.api.pocket.network"
bsc = "https://bsc-testnet.drpc.org"